name: Generate PDF Guide
on: [push]
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate PDF
        uses: docker://pandoc/core:latest
        with:
          args: >
            docs/*.md
            -o System-Setup-Guide.pdf
            --pdf-engine=xelatex
      - uses: actions/upload-artifact@v3
        with:
          name: security-guide
          path: System-Setup-Guide.pdf
